package com.example.weatherapp.ui.theme

import androidx.compose.ui.graphics.Color


//val Purple200 = Color(0xFFBB86FC)
//val Purple500 = Color(0xFF6200EE)
//val Purple700 = Color(0xFF3700B3)
//val Teal200 = Color(0xFF03DAC5)
//val White = Color(0xFFFFFFFF)
//val Black = Color(0xFF000000)
//val DarkGrey = Color(0xFF636363)
//val Primary = Color(0xFF47B9D4)
//val PrimaryDark = Color(0xFF339CB8)
//val LightText = Color(0xFF929292)
//val LightIcon = Color(0xFF767676)
//val PrimaryBackground = Color(0xFFF3F3FB)

val theme_light_primary = Color(0xFF32BE7D)
val theme_light_onPrimary = Color(0xFFFFFFFF)
val theme_light_primaryContainer = Color(0xFF32493C)
val theme_light_onPrimaryContainer = Color(0xFFFFFFFF)
val theme_light_secondary = Color(0xFF95BDA0)
val theme_light_onSecondary = Color(0xFF000000)
val theme_light_secondaryContainer = Color(0xFF164122)
val theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val theme_light_tertiary = Color(0xFF3E6365)
val theme_light_onTertiary = Color(0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(0xFFC9D5D0)
val theme_light_onTertiaryContainer = Color(0xFF163A22)
val theme_light_surface = Color(0xFFFFFFFF)
val theme_light_onSurface = Color(0xFF204A0B)
val theme_light_surfaceContainer = Color(0xFFE6ECE8)
val theme_light_onSurfaceContainer = Color(0xFF204A0B)
val theme_light_error = Color(0xFFB3261E)
val theme_light_onError = Color(0xFFFFFFFF)

val theme_dark_primary = Color(0xFFB3FDC1)
val theme_dark_onPrimary = Color(0xFF000000)
val theme_dark_primaryContainer = Color(0xFF07A88B)
val theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val theme_dark_secondary = Color(0xFFE8FACB)
val theme_dark_onSecondary = Color(0xFF000000)
val theme_dark_secondaryContainer = Color(0xFF7D9457)
val theme_dark_onSecondaryContainer = Color(0xFFFFFFFF)
val theme_dark_tertiary = Color(0xFF3E6365)
val theme_dark_onTertiary = Color(0xFFFFFFFF)
val theme_dark_tertiaryContainer = Color(0xFFC9D5D0)
val theme_dark_onTertiaryContainer = Color(0xFF163A22)
val theme_dark_surface = Color(0xFF000000)
val theme_dark_onSurface = Color(0xFFF0FFEB)
val theme_dark_surfaceContainer = Color(0xFF4E514D)
val theme_dark_onSurfaceContainer = Color(0xFFF0FFEB)
val theme_dark_error = Color(0xFFF2B8B5)
val theme_dark_onError = Color(0xFF601410)
